# Generated by Django 5.0.4 on 2024-05-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.TextField(default='0.00', max_length=100),
        ),
    ]
