# Generated by Django 5.0.4 on 2024-05-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_book_available_alter_book_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.CharField(default='Available', max_length=10),
        ),
    ]
