# Generated by Django 5.0.4 on 2024-05-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_alter_book_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.CharField(blank=True, default='Available', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='section',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
    ]
